### ISSUE TITLE
Packer class not compatible anymore with Spree 2.4

### ISSUE THREAD

**Issue by mickeyren** [spree-contrib/spree-product-assembly#100]
A call to product_assembly_package is completely incompatible with spree 2.4. The current Packer class still expects an order and loops through line items but the one in 2.4 no longer accepts an order instance and uses inventory_units to loop through

Also goes the same with the AssemblyPrioritizer where a call to Adjuster.new is not conforming to the revised Adjuster class on Spree 2.4.

I'm wondering if there's any plan to update this in the near future?

**Comment by huoxito** [comment]
current master should be 2.4 compatible, 2-4-stable branch coming soon, cheers
