### ISSUE TITLE
Duplicate migration file when trying to incorporate spree-product-assembly module into Spree 3.0.0.rc2

### ISSUE THREAD

**Issue by cindyward1** [spree-contrib/spree-product-assembly#102]
There is a migration file in the spree install (<timestamp>_add_line_item_id_to_spree_inventory_units.spree.rb) that has the same class and file names and adds the same column and index as 20130614141524_add_line_item_id_to_spree_inventory_units.rb, plus the spree migration file updates shipment line items. This migration file in spree-product-assembly needs to be deleted.

**Comment by jozw** [comment]
:+1:

**Comment by huoxito** [comment]
fixed on master thanks
