### ISSUE TITLE
Testing of new master branch requires phantomjs

### ISSUE THREAD

**Issue by cindyward1** [spree-contrib/spree-product-assembly#108]
It is necessary to install phantomjs (via brew install on MacOS X) to successfully execute the tests for the new master branch because the feature testing has been moved from webdriver/selenium to poltergeist/phantomjs. Not installing phantomjs will result in errors from Cliver. This should probably be documented since it is a significant (albeit welcome) change. (The headless tests run much faster now.)

Please note that it is unnecessary to install the phantomjs gem and/or specify it in the gemspec.

**Comment by futhr** [comment]
Hi, it use headless, same as most Spree gems. Closing this due to its info is not very specific for this repository, thanks.
