### ISSUE TITLE
uninitialized constant Spree::Wombat::ShipmentSerializer

### ISSUE THREAD

**Issue by Salet** [spree-contrib/spree-product-assembly#110]
Hi. I'm trying to incorporate this extension into fresh Spree 2.4.5 store. It seems to be working fine on my development machine using the master branch.

However, during the build on the staging server I get this error:
```
/home/slimonline/.rvm/gems/ruby-2.0.0-p0@slimonline/bundler/gems/spree-product-assembly-6debe07896d1/app/serializers/spree/wombat/assembly_shipment_serializer.rb:3:in `<module:Wombat>': uninitialized constant Spree::Wombat::ShipmentSerializer (NameError)
	from /home/slimonline/.rvm/gems/ruby-2.0.0-p0@slimonline/bundler/gems/spree-product-assembly-6debe07896d1/app/serializers/spree/wombat/assembly_shipment_serializer.rb:2:in `<module:Spree>'
	from /home/slimonline/.rvm/gems/ruby-2.0.0-p0@slimonline/bundler/gems/spree-product-assembly-6debe07896d1/app/serializers/spree/wombat/assembly_shipment_serializer.rb:1:in `<top (required)>'
```
There's a notice in the documentation about using this with Wombat, but I'm not using it (at least I think I don't). Do I need to add wombat to my gemfile? If so, why is this working in dev?

**Comment by jumph4x** [comment]
Potentially related to the fact that 6debe07896d1 (master tip) is post Spree 2.4 integration work. Try rolling back to before that set of commits.

**Comment by JDutil** [comment]
If you're on a 2.1.5 app (not sure why that would be fresh) you should try the 2-1-stable branch not master.

**Comment by Salet** [comment]
I'm on the 2.4.5 version, not 2.1. My bad. Will try 2.4-beta branch this evening and will let you know.

**Comment by Salet** [comment]
It looks like 5c6eb7cc9921f7289fd564989f233343475b50a6 on master fixed my problem.

**Comment by yf6** [comment]
This is happening again on 2-4-beta with 5c8b9bf undoing 5c6eb7c :(

**Comment by JDutil** [comment]
@yf6 I would make sure your actually on the latest 2-4-beta the fix should still be in place there.

**Comment by yf6** [comment]
@JDutil I'm on latest 2-4-beta, and nope the check of if defined is not there https://github.com/spree-contrib/spree-product-assembly/blob/2-4-beta/app/serializers/spree/wombat/assembly_shipment_serializer.rb

**Comment by JDutil** [comment]
The check should not matter as the serializer is not loaded unless your using spree_wombat:
https://github.com/spree-contrib/spree-product-assembly/blob/master/lib/spree_product_assembly/engine.rb#L12

**Comment by yf6** [comment]
This is interesting. I realized that the AssemblyShipmentSerializer wasn't required by the line you mentioned, but actually by polyglot. I'll go debug it more, not sure if it's something related to this gem anymore, but just in case:
```
...assembly_shipment_serializer.rb:3:in `<module:Wombat>': uninitialized constant Spree::Wombat::ShipmentSerializer (NameError)
	from .../gems/spree-product-assembly-90475e4c1d92/app/serializers/spree/wombat/assembly_shipment_serializer.rb:2:in `<module:Spree>'
	from .../gems/spree-product-assembly-90475e4c1d92/app/serializers/spree/wombat/assembly_shipment_serializer.rb:1:in `<top (required)>'
	from .../lib/ruby/gems/2.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
```

**Comment by BeDepraved** [comment]
I'm running into this same issue. I have a post on stack exchange

http://stackoverflow.com/questions/32492557/spree-product-assembly-crashes-in-production

I know it says this is closed, but this is still happening on my install.

**Comment by yf6** [comment]
@BeDepraved I don't think I ever fully resolved the issue, ended up just including the wombat gem to get things going. :(

**Comment by BeDepraved** [comment]
Well that did it @yf6 thank you for the response. Never even crossed my mind. Thought I don't need wombat so...

**Comment by yf6** [comment]
yeah we are not using wombat either, but hey that fixed it - definitely feels dirty doing that though :-P

**Comment by inyerade** [comment]
install wombat gem is a workaround but not a fix.
