### ISSUE TITLE
Roadmap to 3.0 Compatibility?

### ISSUE THREAD

**Issue by interhive** [spree-contrib/spree-product-assembly#114]
Curious if any one has gotten spree-product-assembly working with Spree 3.0. Not sure if there were any breaking changes in the newest release but I thought I'd ask.

**Comment by JDutil** [comment]
If it's working with 2.4.x then it should be okay I haven't used it though, but there are probably some view markup related changes required to make it look nice with the new bootstrap admin.

**Comment by cindyward1** [comment]
I have spree-product-assembly working successfully with the Spree 3-0-stable branch. As [JDUtil](https://github.com/JDutil) correctly stated above, the vast majority of the work is porting the views to bootstrap. I have most of them done with just 1 or 2 left to do.

With respect to breaking changes, there is a problem introduced by Spree 3 when updating the track_inventory flag on the stock page. (This is actually **NOT** related to spree-product assembly but someone could think that it was.) The ajax call to update the flag was failing with a routing error, resulting in a 500 return code, and the flag could not be updated. My manager and I found and fixed the problem, and his spree pull request [#6286](https://github.com/spree/spree/pull/6286) has been accepted and incorporated into master and 3-0-stable.

**Comment by cindyward1** [comment]
One of the views with which I had not dealt is parts index, and I've been working on it today. The code in that view that adds a part doesn't work at all, which I am trying to fix.
