### ISSUE TITLE
Spree 3-0-stable: checkout_spec.rb fails because mailer's from: is not set

### ISSUE THREAD

**Issue by cindyward1** [spree-contrib/spree-product-assembly#115]
When I run checkout_spec.rb using Spree 3-0-stable, I get the following errors twice:

An error occurred in an after hook
    RuntimeError: AJAX request took longer than 5 seconds.
    occurred at /Users/cindytrialguides/spree-product-assembly/vendor/ruby/2.2.0/bundler/gems/spree-390f5c63a637/core/lib/spree/testing_support/capybara_ext.rb:109:in `wait_for_ajax'

  An error occurred in an after hook
    ArgumentError: An SMTP From address is required to send a message. Set the message smtp_envelope_from, return_path, sender, or from address.
    occurred at /Users/cindytrialguides/spree-product-assembly/vendor/ruby/2.2.0/gems/mail-2.6.3/lib/mail/check_delivery_params.rb:5:in `check_delivery_params'

When I save_and_open_page, the SMTP error appears as follows:

Internal Server Error
An SMTP From address is required to send a message. Set the message smtp_envelope_from, return_path, sender, or from address.
WEBrick/1.3.1 (Ruby/2.2.0/2014-12-25) at 127.0.0.1:52229

The spec runs successfully with the latest Spree 2-4-stable.

**Comment by maralik** [comment]
As I see the spree-product-assembly is depended on spree_backend 2.4.0 is'n it? How is possible to run this with Spree 3-0 stable? Thanks

**Comment by cindyward1** [comment]
I started to port spree-product-assembly to Spree 3-0-stable in April. I had the interactive portions working but all of the interactive testing was failing and about another two dozen test cases were failing. Then I was laid off in mid-May so I haven't done much with Spree 3 since then. 

If you want to work with my port to Spree 3-0-stable, you can clone from my cindyward1 repository on github. Please note that my port incorporates my Spree 2-4-stable spree-product-assembly pull request to use the value of the track_inventory flag on the master variant of the assembly to determine whether inventory should be tracked using the assembly (true) or the parts (false).
There is also a gentleman named Adam working on my Spree 3-0-stable port but I haven't heard from him in a while. PLMK if you need more information ... Cindy
 


     On Monday, July 20, 2015 2:16 AM, maralik <notifications@github.com> wrote:
   

 As I see the spree-product-assembly is depended on spree_backend 2.4.0 is'n it? How is possible to run this with Spree 3-0 stable? Thanks—

**Comment by maralik** [comment]
great, thanks!

**Comment by futhr** [comment]
Hi, since commit https://github.com/spree-contrib/spree-product-assembly/commit/d72ffb594cdded7a7b2d193347788fe0950545b3 this information concerning the fork is not very up-to-date with `spree-contrib` `master` branch and thereby ambiguous.
