### ISSUE TITLE
ETA on 3-0-stable compatibility?

### ISSUE THREAD

**Issue by interhive** [spree-contrib/spree-product-assembly#123]
I see work is being done to bring this up to 3-0-stable compatibility. Is there an ETA on this being completed?

Thanks for an awesome gem!

**Comment by vinniefranco** [comment]
@interhive plugging away at it. The branch is nearly ready, just dealing with all the things that came with the switch to bootstrap within the admin.

**Comment by cshapeshifter** [comment]
How is progress on this coming along? Is there anything specifically that we could help with? Are there any 3.0 related issues on the tracker? This is a very useful extension indeed.

**Comment by vinniefranco** [comment]
It's in! Let me close out this issue to clarify that
