### ISSUE TITLE
Parts should be linked to Variants instead of Products.

### ISSUE THREAD

**Issue by nishant-cyro** [spree-contrib/spree-product-assembly#132]
Parts should be linked to variants instead of products, because there may be a case that someone wants to sell a few variants of a product-assembly like a restaurant can sell a few variants of a meal - Meal with Sprite, Meal with Coke and Meal with Sprite.

So, we should allow different variants to be assembly of different parts.

**Comment by nishant-cyro** [comment]
@priyank-gupta @Mafi88 @damianlegawiec - Any thoughts?

**Comment by jhonein** [comment]
Yes I am looking for the same, I am willing to pay a developer to extend this extension to make it on the level of the variants. I already worked on the UI of how it's going to be. I need someone to connect it to the backend.

I added the dummy column Variant in the following attached file.
<img width="810" alt="variant" src="https://cloud.githubusercontent.com/assets/590998/13261600/c728e5c6-da15-11e5-9a7a-0bc2d1e35c29.png">

**Comment by priyank-gupta** [comment]
@nishant-cyro I think this should be included.

**Comment by nishant-cyro** [comment]
@priyank-gupta @jhonein - Cool, I will implement this one and raise a PR soon.

**Comment by jhonein** [comment]
wow guys that's great! See attached, this is a modified pull from version 821b80f235d572e0fc3d4445116a09a58e09765a. you are welcome to diff them to see the changes.
[spree-product-assembly-extension.zip](https://github.com/spree-contrib/spree-product-assembly/files/144748/spree-product-assembly-extension.zip)

This version add the dropdown list and the variant column on the UI. You are welcome to modify it from here.

**Comment by qinghe** [comment]
@nishant-cyro @jhonein ，as @priyank-gupta said, it is already implemented. Just use it.
I am David @jhonein

**Comment by damianlegawiec** [comment]
Done via https://github.com/spree-contrib/spree-product-assembly/pull/136
