### ISSUE TITLE
Disabling of before_payment state eliminates payment_sources

### ISSUE THREAD

**Issue by jkelleyj** [spree-contrib/spree-product-assembly#140]
This override of before_payment in the checkout controller breaks saved payment sources:

https://github.com/spree-contrib/spree-product-assembly/blob/master/app/controllers/spree/checkout_controller_decorator.rb#L6

In spree/frontend, the before_payment method does two things:
1) handles removal of products for packaging
2) loads @payment_sources for the current spree user

I'd propose that we find an alternative approach to allow the product assembly to opt out of being processed by the stock differentiator.

**Comment by bjsion** [comment]
I have the same issue as the OP. What I did for now is to override the `remove` method of the `OrderContents` class to ignore a product assemblies using the `variant.product.assembly?`, like so:
```ruby
Spree::OrderContents.class_eval do
  def remove(variant, quantity = 1, options = {})
    if !variant.product.assembly?
      line_item = remove_from_line_item(variant, quantity, options)
      after_add_or_remove(line_item, options)
    end
  end
end
```

Then I re-enabled the `before_payment` on the `CheckoutController`

**Comment by jkelleyj** [comment]
Noticed this is a duplicate of #98 thanks @bjsion for the approach. This seems better than "reoverriding" the checkout controller decorator.

**Comment by bjsion** [comment]
No worries. Hope it helps and can make it back into the mainline. I am too busy at the moment make a patch and test.
