### ISSUE TITLE
spree 3.3 compatible? 

### ISSUE THREAD

**Issue by joshRpowell** [spree-contrib/spree-product-assembly#160]
will this extension be updated to the new dependency standard? https://github.com/spree/spree/blob/master/guides/content/release_notes/3_3_0.md#update-your-extensions

**Comment by damianlegawiec** [comment]
@joshRpowell yep, all major extensions will get Rails 5.1 fixes before the final Spree 3.3.0 release

**Comment by javogel** [comment]
Hi @damianlegawiec, any idea when we could expect this  to work with Rails 5.1 and Spree 3.3? I've been having several issues with this extension as well as some others. I've forked the repo in order to try to fix some of the problems, but still working through it.  Thanks!

**Comment by joshRpowell** [comment]
working for me now.
Rails 5.1 & Spree 3.4
